apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mayank-mishrainfra360.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mayank-mishrainfra360.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "mayank-mishrainfra360.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8080