apiVersion: v1
kind: Service
metadata:
  name: {{ include "mayank-mishrainfra360.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    app: {{ include "mayank-mishrainfra360.name" . }}-frontend